export function Data1() {
  const data = {
    title: "홈투데이",
    screen_name: "TODAY",
    view_event_logging: {},
    logging: {
      SCREEN: "TODAY",
    },
    components: [
      {
        component_id: 128,
        type: {
          header: null,
          item_list: "TWO_COL_CARD_LIST",
          footer: null,
        },
        logging: {
          analytics: {
            LIST_ID: "today_recommend",
          },
          inhouse: {
            list_id: "today_recommend",
          },
        },
        entity: {
          header: null,
          item_list: [
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 16391373,
                  name: "[반팔티종결!/코디필수템] 내가 찾던 기본티, 부드러운 무지 라운드 반팔티셔츠 (11color)",
                  market_sno: 2466,
                  market_name: "앤드모어",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/7ZkHJXG38JY/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzgxNzRkYWViOTMzZWNlMDQwZGY5NDFmYTM3MjY3OWY2LmdpZg",
                  closed_reason: null,
                  sell_count: 63320,
                  delivery_type: "shak",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 9900,
                  discount_rate: 17,
                  like: {
                    goods_sno: 16391373,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 3,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/16391373/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "반소매티셔츠",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/16391373/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "16391373",
                    GOODS_NAME:
                      "[반팔티종결!/코디필수템] 내가 찾던 기본티, 부드러운 무지 라운드 반팔티셔츠 (11color)",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "2466",
                    MARKET_NAME: "앤드모어",
                    CATEGORY_SNO: "18",
                    CATEGORY_NAME: "반소매티셔츠",
                    STANDARD_CATEGORY_SNO: "14",
                    STANDARD_CATEGORY_NAME: "반소매티셔츠",
                    DISCOUNT_RATE: 17,
                    SALES_PRICE: 9900,
                    SALES_PRICE_RANGE: "5,001~10,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "shak",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 7110,
                    REVIEW_COUNT_RANGE: "7,101~7,150",
                    REVIEW_RATING: 94,
                    LIKES_COUNT: 88431,
                    LIKES_COUNT_RANGE: "88,401~88,450",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 3,
                    SEASON: ["summer"],
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 16391373,
                    list_id: "today_recommend",
                    list_index: 3,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/7ZkHJXG38JY/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzgxNzRkYWViOTMzZWNlMDQwZGY5NDFmYTM3MjY3OWY2LmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "[반팔티종결!/코디필수템] 내가 찾던 기본티, 부드러운 무지 라운드 반팔티셔츠 (11color)",
                    price: "9,900",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "17%",
                    closed_reason: null,
                    image_badge:
                      "https://d3ha2047wt6x28.cloudfront.net/ws4iGPA2VJg/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2Vfc2hha19kZWxpdmVyeS5wbmc",
                    image_badge_width: 43,
                    image_badge_height: 18,
                    chips: null,
                    market_name: "앤드모어",
                    store_text: "앤드모어",
                    nudging_text: "63,320개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 18525942,
                  name: "[유니크힙/박스핏!]608배색나그랑프린팅오버핏반팔티(4color)",
                  market_sno: 2032,
                  market_name: "꼬맹",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/WUf0tgCNQvU/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2I5NWNlZTNkYjViNmZkYWVhM2Y1ODIzYTMyMzJmY2Q2LmdpZg",
                  closed_reason: null,
                  sell_count: 3538,
                  delivery_type: "standard",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 13610,
                  discount_rate: 23,
                  like: {
                    goods_sno: 18525942,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 4,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/18525942/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "반소매티셔츠",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/18525942/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "18525942",
                    GOODS_NAME:
                      "[유니크힙/박스핏!]608배색나그랑프린팅오버핏반팔티(4color)",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "2032",
                    MARKET_NAME: "꼬맹",
                    CATEGORY_SNO: "18",
                    CATEGORY_NAME: "반소매티셔츠",
                    STANDARD_CATEGORY_SNO: "14",
                    STANDARD_CATEGORY_NAME: "반소매티셔츠",
                    DISCOUNT_RATE: 23,
                    SALES_PRICE: 13610,
                    SALES_PRICE_RANGE: "10,001~15,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "standard",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 92,
                    REVIEW_COUNT_RANGE: "51~100",
                    REVIEW_RATING: 100,
                    LIKES_COUNT: 9894,
                    LIKES_COUNT_RANGE: "9,851~9,900",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 4,
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 18525942,
                    list_id: "today_recommend",
                    list_index: 4,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/WUf0tgCNQvU/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2I5NWNlZTNkYjViNmZkYWVhM2Y1ODIzYTMyMzJmY2Q2LmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "[유니크힙/박스핏!]608배색나그랑프린팅오버핏반팔티(4color)",
                    price: "13,610",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "23%",
                    closed_reason: null,
                    image_badge: null,
                    image_badge_width: null,
                    image_badge_height: null,
                    chips: null,
                    market_name: "꼬맹",
                    store_text: "꼬맹",
                    nudging_text: "3,538개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 19108474,
                  name: "**정품/주문폭주!/유사품주의** 포레 스트라이프 짐색 스트링백 백팩 가방",
                  market_sno: 18114,
                  market_name: "시프트에잇",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/5QgUPHimwOo/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2Q0MWY0ZGIxNzYxZmNlOGIzODIxNDVlMjIzMzI2ODQ2LmdpZg",
                  closed_reason: null,
                  sell_count: 5230,
                  delivery_type: "standard",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 17900,
                  discount_rate: 10,
                  like: {
                    goods_sno: 19108474,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 5,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/19108474/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "백팩",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/19108474/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "19108474",
                    GOODS_NAME:
                      "**정품/주문폭주!/유사품주의** 포레 스트라이프 짐색 스트링백 백팩 가방",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "18114",
                    MARKET_NAME: "시프트에잇",
                    CATEGORY_SNO: "487",
                    CATEGORY_NAME: "백팩",
                    STANDARD_CATEGORY_SNO: "43",
                    STANDARD_CATEGORY_NAME: "백팩",
                    DISCOUNT_RATE: 10,
                    SALES_PRICE: 17900,
                    SALES_PRICE_RANGE: "15,001~20,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "standard",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 6,
                    REVIEW_COUNT_RANGE: "1~50",
                    REVIEW_RATING: 100,
                    LIKES_COUNT: 30317,
                    LIKES_COUNT_RANGE: "30,301~30,350",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 5,
                    SEASON: ["summer"],
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 19108474,
                    list_id: "today_recommend",
                    list_index: 5,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/5QgUPHimwOo/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2Q0MWY0ZGIxNzYxZmNlOGIzODIxNDVlMjIzMzI2ODQ2LmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "**정품/주문폭주!/유사품주의** 포레 스트라이프 짐색 스트링백 백팩 가방",
                    price: "17,900",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "10%",
                    closed_reason: null,
                    image_badge: null,
                    image_badge_width: null,
                    image_badge_height: null,
                    chips: null,
                    market_name: "시프트에잇",
                    store_text: "시프트에잇",
                    nudging_text: "5,230개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 19607506,
                  name: "[레이어드/여름셋업/청청/휴가룩] 티도 프릴 생지 데님 뷔스티에 블라우스+밴딩 와이드 팬츠 set (2color)",
                  market_sno: 4696,
                  market_name: "더핑크",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/t2j7VGo6yBA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjJhNzI1NjhiMThiY2JkM2ZhNmE0NGJkMDg1NWE4LmdpZg",
                  closed_reason: null,
                  sell_count: 500,
                  delivery_type: "standard",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 27710,
                  discount_rate: 37,
                  like: {
                    goods_sno: 19607506,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 6,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/19607506/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "투피스",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/19607506/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "19607506",
                    GOODS_NAME:
                      "[레이어드/여름셋업/청청/휴가룩] 티도 프릴 생지 데님 뷔스티에 블라우스+밴딩 와이드 팬츠 set (2color)",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "4696",
                    MARKET_NAME: "더핑크",
                    CATEGORY_SNO: "208",
                    CATEGORY_NAME: "투피스",
                    STANDARD_CATEGORY_SNO: "34",
                    STANDARD_CATEGORY_NAME: "데님 투피스",
                    DISCOUNT_RATE: 37,
                    SALES_PRICE: 27710,
                    SALES_PRICE_RANGE: "25,001~30,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "standard",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 0,
                    REVIEW_COUNT_RANGE: "0",
                    REVIEW_RATING: 0,
                    LIKES_COUNT: 1848,
                    LIKES_COUNT_RANGE: "1,801~1,850",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 6,
                    SEASON: ["summer"],
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 19607506,
                    list_id: "today_recommend",
                    list_index: 6,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/t2j7VGo6yBA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjJhNzI1NjhiMThiY2JkM2ZhNmE0NGJkMDg1NWE4LmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "[레이어드/여름셋업/청청/휴가룩] 티도 프릴 생지 데님 뷔스티에 블라우스+밴딩 와이드 팬츠 set (2color)",
                    price: "27,710",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "37%",
                    closed_reason: null,
                    image_badge: null,
                    image_badge_width: null,
                    image_badge_height: null,
                    chips: null,
                    market_name: "더핑크",
                    store_text: "더핑크",
                    nudging_text: "500개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 19926723,
                  name: "**🔥당일출고🔥정품/유사품주의!** 피노 스트라이프 짐색 스트링백 복조리백 백팩 힙한 단가라 캔버스 가방",
                  market_sno: 1236,
                  market_name: "비마이뮤즈",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/5f-XhMhbwkE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFlMDk5NmY3NTRkNGM0ZWI2MzFjZmE5MThiNDEwYzE0LmpwZw",
                  closed_reason: null,
                  sell_count: 328,
                  delivery_type: "standard",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 11900,
                  discount_rate: 40,
                  like: {
                    goods_sno: 19926723,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 7,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/19926723/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "백팩",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/19926723/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "19926723",
                    GOODS_NAME:
                      "**🔥당일출고🔥정품/유사품주의!** 피노 스트라이프 짐색 스트링백 복조리백 백팩 힙한 단가라 캔버스 가방",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "1236",
                    MARKET_NAME: "비마이뮤즈",
                    CATEGORY_SNO: "487",
                    CATEGORY_NAME: "백팩",
                    STANDARD_CATEGORY_SNO: "43",
                    STANDARD_CATEGORY_NAME: "백팩",
                    DISCOUNT_RATE: 40,
                    SALES_PRICE: 11900,
                    SALES_PRICE_RANGE: "10,001~15,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "standard",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 4,
                    REVIEW_COUNT_RANGE: "1~50",
                    REVIEW_RATING: 100,
                    LIKES_COUNT: 724,
                    LIKES_COUNT_RANGE: "701~750",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 7,
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 19926723,
                    list_id: "today_recommend",
                    list_index: 7,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/5f-XhMhbwkE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFlMDk5NmY3NTRkNGM0ZWI2MzFjZmE5MThiNDEwYzE0LmpwZw",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "**🔥당일출고🔥정품/유사품주의!** 피노 스트라이프 짐색 스트링백 복조리백 백팩 힙한 단가라 캔버스 가방",
                    price: "11,900",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "40%",
                    closed_reason: null,
                    image_badge: null,
                    image_badge_width: null,
                    image_badge_height: null,
                    chips: null,
                    market_name: "비마이뮤즈",
                    store_text: "비마이뮤즈",
                    nudging_text: "328개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 19239878,
                  name: "🔥주문폭주🔥 빈티지 여리 니트 가디건 NB361",
                  market_sno: 44868,
                  market_name: "니블리",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/wN7555nK8jI/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzRjNzNlNjAxMjI0MjMyYTY4Zjg1ZjM3OWI2ZTczZTIzLmdpZg",
                  closed_reason: null,
                  sell_count: 500,
                  delivery_type: "standard",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 25800,
                  discount_rate: 0,
                  like: {
                    goods_sno: 19239878,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 8,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/19239878/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "가디건",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/19239878/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "19239878",
                    GOODS_NAME: "🔥주문폭주🔥 빈티지 여리 니트 가디건 NB361",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "44868",
                    MARKET_NAME: "니블리",
                    CATEGORY_SNO: "16",
                    CATEGORY_NAME: "가디건",
                    STANDARD_CATEGORY_SNO: "3",
                    STANDARD_CATEGORY_NAME: "가디건",
                    DISCOUNT_RATE: 0,
                    SALES_PRICE: 25800,
                    SALES_PRICE_RANGE: "25,001~30,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "standard",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 2,
                    REVIEW_COUNT_RANGE: "1~50",
                    REVIEW_RATING: 100,
                    LIKES_COUNT: 1754,
                    LIKES_COUNT_RANGE: "1,751~1,800",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 8,
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 19239878,
                    list_id: "today_recommend",
                    list_index: 8,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/wN7555nK8jI/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzRjNzNlNjAxMjI0MjMyYTY4Zjg1ZjM3OWI2ZTczZTIzLmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "🔥주문폭주🔥 빈티지 여리 니트 가디건 NB361",
                    price: "25,800",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: null,
                    closed_reason: null,
                    image_badge: null,
                    image_badge_width: null,
                    image_badge_height: null,
                    chips: null,
                    market_name: "니블리",
                    store_text: "니블리",
                    nudging_text: "500개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 18127633,
                  name: "스모킹업 니코틴제거 연초 담배필터 금연필터 100개입",
                  market_sno: 30692,
                  market_name: "쓴다몰",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/Rz4B2XhYDwU/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzNlZGM0NjI2NWNlMDBkMGM5NTc3YmFhZGMzYzdiNzlmLmpwZw",
                  closed_reason: null,
                  sell_count: 862,
                  delivery_type: "quick",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 12900,
                  discount_rate: 0,
                  like: {
                    goods_sno: 18127633,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 9,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/18127633/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "라이프",
                  category_name: "기타소품",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/18127633/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "18127633",
                    GOODS_NAME:
                      "스모킹업 니코틴제거 연초 담배필터 금연필터 100개입",
                    MARKET_TYPE: "라이프",
                    MARKET_SNO: "30692",
                    MARKET_NAME: "쓴다몰",
                    CATEGORY_SNO: "532",
                    CATEGORY_NAME: "기타소품",
                    STANDARD_CATEGORY_SNO: "553",
                    STANDARD_CATEGORY_NAME: "기타",
                    DISCOUNT_RATE: 0,
                    SALES_PRICE: 12900,
                    SALES_PRICE_RANGE: "10,001~15,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "quick",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "2",
                    REVIEW_COUNT: 7,
                    REVIEW_COUNT_RANGE: "1~50",
                    REVIEW_RATING: 71,
                    LIKES_COUNT: 5404,
                    LIKES_COUNT_RANGE: "5,401~5,450",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 9,
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 18127633,
                    list_id: "today_recommend",
                    list_index: 9,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/Rz4B2XhYDwU/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzNlZGM0NjI2NWNlMDBkMGM5NTc3YmFhZGMzYzdiNzlmLmpwZw",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "스모킹업 니코틴제거 연초 담배필터 금연필터 100개입",
                    price: "12,900",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: null,
                    closed_reason: null,
                    image_badge:
                      "https://d3ha2047wt6x28.cloudfront.net/SdBe7NC7kt4/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfcXVpY2tfZGVsaXZlcnkucG5n",
                    image_badge_width: 46,
                    image_badge_height: 18,
                    chips: null,
                    market_name: "쓴다몰",
                    store_text: "쓴다몰",
                    nudging_text: "862개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 18429462,
                  name: "[핏예술/기장선택/쿨링원단/이염방지] 토루 쿨 하이웨스트 밴딩 와이드 데님 팬츠 (2color)",
                  market_sno: 4696,
                  market_name: "더핑크",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/rNYKE8M8NYc/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzRkZWFmYWQ0ZDZlMTU0MmYxZGE4ZDk5MjlmMGYzYzk2LmdpZg",
                  closed_reason: null,
                  sell_count: 8428,
                  delivery_type: "standard",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 19990,
                  discount_rate: 40,
                  like: {
                    goods_sno: 18429462,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 10,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/18429462/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "데님",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/18429462/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "18429462",
                    GOODS_NAME:
                      "[핏예술/기장선택/쿨링원단/이염방지] 토루 쿨 하이웨스트 밴딩 와이드 데님 팬츠 (2color)",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "4696",
                    MARKET_NAME: "더핑크",
                    CATEGORY_SNO: "501",
                    CATEGORY_NAME: "데님",
                    STANDARD_CATEGORY_SNO: "75",
                    STANDARD_CATEGORY_NAME: "데님 롱팬츠",
                    DISCOUNT_RATE: 40,
                    SALES_PRICE: 19990,
                    SALES_PRICE_RANGE: "15,001~20,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "standard",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 410,
                    REVIEW_COUNT_RANGE: "401~450",
                    REVIEW_RATING: 92,
                    LIKES_COUNT: 21712,
                    LIKES_COUNT_RANGE: "21,701~21,750",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 10,
                    SEASON: ["summer"],
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 18429462,
                    list_id: "today_recommend",
                    list_index: 10,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/rNYKE8M8NYc/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzRkZWFmYWQ0ZDZlMTU0MmYxZGE4ZDk5MjlmMGYzYzk2LmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "[핏예술/기장선택/쿨링원단/이염방지] 토루 쿨 하이웨스트 밴딩 와이드 데님 팬츠 (2color)",
                    price: "19,990",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "40%",
                    closed_reason: null,
                    image_badge: null,
                    image_badge_width: null,
                    image_badge_height: null,
                    chips: null,
                    market_name: "더핑크",
                    store_text: "더핑크",
                    nudging_text: "8,428개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 18780603,
                  name: "당일발송🚀[여름자켓💙/데일리템!] 라이킷 투포켓 크롭 반팔 데님 셔츠 남방 청자켓",
                  market_sno: 23347,
                  market_name: "자스민벨",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/npyMZPPpXZQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ExMjlmOWVhMWQ5OTQ1YjU0MmUzMWFjNDIwZjE4ZDg3LmdpZg",
                  closed_reason: null,
                  sell_count: 1113,
                  delivery_type: "quick",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 21750,
                  discount_rate: 27,
                  like: {
                    goods_sno: 18780603,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 11,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/18780603/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "자켓",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/18780603/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "18780603",
                    GOODS_NAME:
                      "당일발송🚀[여름자켓💙/데일리템!] 라이킷 투포켓 크롭 반팔 데님 셔츠 남방 청자켓",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "23347",
                    MARKET_NAME: "자스민벨",
                    CATEGORY_SNO: "293",
                    CATEGORY_NAME: "자켓",
                    STANDARD_CATEGORY_SNO: "5",
                    STANDARD_CATEGORY_NAME: "데님 자켓",
                    DISCOUNT_RATE: 27,
                    SALES_PRICE: 21750,
                    SALES_PRICE_RANGE: "20,001~25,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "quick",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 3,
                    REVIEW_COUNT_RANGE: "1~50",
                    REVIEW_RATING: 100,
                    LIKES_COUNT: 5448,
                    LIKES_COUNT_RANGE: "5,401~5,450",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 11,
                    SEASON: ["spring", "summer"],
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 18780603,
                    list_id: "today_recommend",
                    list_index: 11,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/npyMZPPpXZQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ExMjlmOWVhMWQ5OTQ1YjU0MmUzMWFjNDIwZjE4ZDg3LmdpZg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "당일발송🚀[여름자켓💙/데일리템!] 라이킷 투포켓 크롭 반팔 데님 셔츠 남방 청자켓",
                    price: "21,750",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "27%",
                    closed_reason: null,
                    image_badge:
                      "https://d3ha2047wt6x28.cloudfront.net/SdBe7NC7kt4/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfcXVpY2tfZGVsaXZlcnkucG5n",
                    image_badge_width: 46,
                    image_badge_height: 18,
                    chips: null,
                    market_name: "자스민벨",
                    store_text: "자스민벨",
                    nudging_text: "1,113개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
            {
              type: "GOODS_CARD",
              item_entity: {
                item: {
                  sno: 18463706,
                  name: "[unisex/힙한빈티지] 도스 나염 프린팅 오버핏 반팔티 (4color)",
                  market_sno: 44178,
                  market_name: "피깁",
                  image:
                    "https://d3ha2047wt6x28.cloudfront.net/-xn6gTJfBsk/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzI3YzM5ZjgxZDRjZTkwZmM3MzFkMGRiYTcyNDBlNDIzLkdJRg",
                  closed_reason: null,
                  sell_count: 8403,
                  delivery_type: "shak",
                  ranking: null,
                  available_only_new_member: false,
                  is_premium_hotdeal: false,
                  is_hotdeal: false,
                  is_new: false,
                  price: 15500,
                  discount_rate: 11,
                  like: {
                    goods_sno: 18463706,
                    is_liked: false,
                    folder_sno: null,
                    referrer: {
                      list_id: "today_recommend",
                      list_index: 12,
                    },
                  },
                  ad: null,
                  on_return: {
                    type: "INJECT",
                    data: {
                      url: "goods/18463706/recommend_related_goods_by_click_for_today/?from=TODAY",
                    },
                  },
                  market_type: "셀럽",
                  category_name: "반소매티셔츠",
                  feedback_type: "default",
                  remote_deeplink:
                    "ably://goods/18463706/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D",
                },
                logging: {
                  analytics: {
                    GOODS_SNO: "18463706",
                    GOODS_NAME:
                      "[unisex/힙한빈티지] 도스 나염 프린팅 오버핏 반팔티 (4color)",
                    MARKET_TYPE: "셀럽",
                    MARKET_SNO: "44178",
                    MARKET_NAME: "피깁",
                    CATEGORY_SNO: "18",
                    CATEGORY_NAME: "반소매티셔츠",
                    STANDARD_CATEGORY_SNO: "14",
                    STANDARD_CATEGORY_NAME: "반소매티셔츠",
                    DISCOUNT_RATE: 11,
                    SALES_PRICE: 15500,
                    SALES_PRICE_RANGE: "15,001~20,000",
                    IS_NEW: "0",
                    DELIVERY_TYPE: "shak",
                    IS_AD: "0",
                    LIST_PARAMS: null,
                    MARKET_TYPE_SNO: "7",
                    REVIEW_COUNT: 335,
                    REVIEW_COUNT_RANGE: "301~350",
                    REVIEW_RATING: 94,
                    LIKES_COUNT: 24023,
                    LIKES_COUNT_RANGE: "24,001~24,050",
                    DELIVERY_SCORE: null,
                    IS_DISCOUNT_END_TEXT_DISPLAYED: false,
                    PROMOTION_TAG: [],
                    LIST_ID: "today_recommend",
                    LIST_INDEX: 12,
                    SEASON: ["summer"],
                    CARD_TYPE: "GOODS_CARD",
                  },
                  inhouse: {
                    goods_sno: 18463706,
                    list_id: "today_recommend",
                    list_index: 12,
                    schema_name: "Goods",
                    pool: "best",
                  },
                },
                render: {
                  type: "MARKET_NUDGING",
                  contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                  size: "MEDIUM",
                  data: {
                    image: {
                      url: "https://d3ha2047wt6x28.cloudfront.net/-xn6gTJfBsk/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzI3YzM5ZjgxZDRjZTkwZmM3MzFkMGRiYTcyNDBlNDIzLkdJRg",
                      use_animation: true,
                      ratio: 1.2,
                    },
                    name: "[unisex/힙한빈티지] 도스 나염 프린팅 오버핏 반팔티 (4color)",
                    price: "15,500",
                    has_ad_badge: false,
                    name_lines: 1,
                    discount_rate: "11%",
                    closed_reason: null,
                    image_badge:
                      "https://d3ha2047wt6x28.cloudfront.net/ws4iGPA2VJg/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2Vfc2hha19kZWxpdmVyeS5wbmc",
                    image_badge_width: 43,
                    image_badge_height: 18,
                    chips: null,
                    market_name: "피깁",
                    store_text: "피깁",
                    nudging_text: "8,403개 구매중",
                    ranking: null,
                    actions: ["LIKE"],
                    discount_end_text: null,
                    top_nudging_text: null,
                  },
                },
              },
            },
          ],
          footer: null,
        },
      },
    ],
    next_token: "eyJsaSI6IDIsICJuIjogImV5SnNZWE4wWDJsdVpHVjRJam9nTVROOSJ9",
    view_event_channels: [
      "firebase",
      "amplitude",
      "ablylog",
      "facebook",
      "appsflyer",
    ],
  };

  return data;
}
